server:
  host: "0.0.0.0"
  port: 8002
  name: "auth2"
  mode: "dev"

mysql:
  dataSourceName: "root:123456@(127.0.0.1:3306)/auth?charset=utf8mb4&parseTime=true&loc=Local"
  maxOpenConns: 20
  maxIdleConns: 10

logger:
  level: "DEBUG"
  filePath: "./log_file"
  fileName: "log.log"
  maxFileSize: 1073741824
  toFile: false

zap:
  level: "DEBUG"
  fileName: "auth.log"
  maxSize: 1073741824
  maxAge: 1024
  maxBackups: 1024

redis:
  addr: "127.0.0.1:6379"
  poolSize: 10
  minIdleConns: 5
  password: ""
  db: 1